function p1=plot_error(x,y,error,color_index)

colors={'salmon','skyblue','palegreen','gold','grey','orange','violet','salmon','skyblue'};
colors2={'darkred','blue','darkgreen','goldenrod','black','orangered','magenta','darkred','blue'};

p1=errorbar(x,y,error, ...
    'Color',rgb(colors2{color_index}), ...
    'Linewidth',1,'LineStyle', 'none');hold on;

set(gca,'fontsize',15,'FontName','MyriadPro-Regular');
set(gca, ...
    'Box' , 'off' , ...
    'TickDir' , 'out' , ...
    'TickLength' , [.02 .02] , ...
    'XMinorTick' , 'on' , ...
    'YMinorTick' , 'on' , ...
    'YGrid' , 'on' , ...
    'XGrid', 'on',...
    'LineWidth' , 1 );
grid on;
end